import { z } from 'zod'

export const loginSchema = z.object({
  username: z.string().min(1, 'Username is required'),
  password: z.string().min(1, 'Password is required'),
  remember: z.boolean().optional(),
})

export const projectSchema = z.object({
  name: z.string().min(2, 'Project name is required'),
  slug: z.string().min(2, 'Slug is required'),
  shortDescription: z.string().min(10, 'Short description is required'),
  description: z.string().min(20, 'Full description is required'),
  city: z.string().min(1, 'City is required'),
  state: z.string().optional(),
  country: z.string().min(1, 'Country is required'),
  status: z.enum(['Completed', 'Upcoming', 'In Progress']),
  category: z.enum([
    'Residential',
    'Commercial',
    'Industrial',
    'Infrastructure',
    'Architecture',
    'Interior',
  ]),
  completionDate: z.string().optional(),
  startDate: z.string().optional(),
  area: z.string().optional(),
  squareFeet: z.string().optional(),
  clientName: z.string().optional(),
  architectName: z.string().optional(),
  budget: z.string().optional(),
  duration: z.string().optional(),
  constructionType: z.string().optional(),
  image: z.string().min(1, 'Cover image is required'),
  thumbnail: z.string().optional(),
  gallery: z.array(z.string()).optional(),
  technologies: z.array(z.string()).optional(),
  materials: z.array(z.string()).optional(),
  challenges: z.array(z.string()).optional(),
  solutions: z.array(z.string()).optional(),
  highlights: z.array(z.string()).optional(),
  seoTitle: z.string().optional(),
  seoDescription: z.string().optional(),
  featured: z.boolean().optional(),
  displayOrder: z.coerce.number().optional(),
  published: z.boolean().optional(),
  draft: z.boolean().optional(),
})

export const serviceSchema = z.object({
  title: z.string().min(2, 'Title is required'),
  slug: z.string().min(2, 'Slug is required'),
  shortDescription: z.string().min(10, 'Short description is required'),
  description: z.string().min(10, 'Description is required'),
  icon: z.string().min(1, 'Icon is required'),
  image: z.string().min(1, 'Image is required'),
  bannerImage: z.string().optional(),
  gallery: z.array(z.string()).optional(),
  features: z.array(z.string()).optional(),
  benefits: z.array(z.string()).optional(),
  displayOrder: z.coerce.number().optional(),
  seoTitle: z.string().optional(),
  seoDescription: z.string().optional(),
  published: z.boolean().optional(),
})

export const teamSchema = z.object({
  name: z.string().min(2, 'Name is required'),
  designation: z.string().min(2, 'Designation is required'),
  department: z.string().optional(),
  biography: z.string().min(10, 'Biography is required'),
  yearsExperience: z.string().optional(),
  specialisations: z.array(z.string()).optional(),
  linkedin: z.string().optional(),
  email: z.string().email('Invalid email').optional().or(z.literal('')),
  phone: z.string().optional(),
  photo: z.string().min(1, 'Photo is required'),
  displayOrder: z.coerce.number().optional(),
  featured: z.boolean().optional(),
  status: z.enum(['Active', 'Inactive']).optional(),
})

export const clientSchema = z.object({
  name: z.string().min(2, 'Client name is required'),
  logoUrl: z.string().optional(),
  websiteUrl: z.string().optional(),
  displayOrder: z.coerce.number().optional(),
  published: z.boolean().optional(),
})

export const settingsSchema = z.object({
  companyName: z.string().min(2, 'Company name is required'),
  shortName: z.string().optional(),
  legalName: z.string().optional(),
  tagline: z.string().optional(),
  description: z.string().optional(),
  email: z.string().email('Valid email required'),
  phone: z.string().min(5, 'Phone is required'),
  phoneRaw: z.string().optional(),
  websiteUrl: z.string().optional(),
  founded: z.coerce.number().optional(),
  footerContent: z.string().optional(),
  copyrightText: z.string().optional(),
  contactNote: z.string().optional(),
  mapEmbedUrl: z.string().optional(),
  mapLabel: z.string().optional(),
  street: z.string().optional(),
  city: z.string().optional(),
  state: z.string().optional(),
  zip: z.string().optional(),
  country: z.string().optional(),
  weekdays: z.string().optional(),
  saturday: z.string().optional(),
  sunday: z.string().optional(),
  linkedin: z.string().optional(),
  instagram: z.string().optional(),
  twitter: z.string().optional(),
  facebook: z.string().optional(),
  youtube: z.string().optional(),
  logoUrl: z.string().optional(),
  logoNavUrl: z.string().optional(),
  faviconUrl: z.string().optional(),
  ogImageUrl: z.string().optional(),
  heroImageUrl: z.string().optional(),
  colorNavy: z.string().optional(),
  colorNavyLight: z.string().optional(),
  colorBrandNavy: z.string().optional(),
  colorPrimary: z.string().optional(),
  colorPrimaryLight: z.string().optional(),
  colorAccent: z.string().optional(),
  colorAccentDeep: z.string().optional(),
  colorLavender: z.string().optional(),
  colorSurface: z.string().optional(),
  seoDefaultTitle: z.string().optional(),
  seoDefaultDescription: z.string().optional(),
})
